platform :ios, '9.0'

flutter_application_path = '../flutter_part/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'NativePart' do
  install_all_flutter_pods(flutter_application_path)
  
  pod 'AFNetworking', '~> 3.0' 
end
